spring.application.name=SmartGuardian Backend

# Database Configuration
# updated to match the running dev container database
spring.datasource.url=jdbc:postgresql://db:5432/fyp_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
securehealthapp.app.jwtSecret=bXlTZWNyZXRLZXk=
securehealthapp.app.jwtExpirationMs=86400000